import { GeneratedData } from '../schemas';

export function generateSqlScript(data: Record<string, GeneratedData>, dbType: string): string {
  let sql = `-- Synthetic Data Generated by Data Generator (Telegram Bot)\n`;
  sql += `-- Database Type: ${dbType}\n\n`;

  for (const [tableName, tableData] of Object.entries(data)) {
    if (tableData.rows.length === 0) continue;

    sql += `-- Data for table ${tableName}\n`;
    
    for (const row of tableData.rows) {
      const values = row.map(val => {
        if (val === null) return 'NULL';
        if (typeof val === 'number') return val.toString();
        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
        if (val instanceof Date) return `'${val.toISOString()}'`;
        // Escape quotes
        const stringVal = String(val).replace(/'/g, "''");
        return `'${stringVal}'`;
      });
      
      sql += `INSERT INTO ${tableName} (${tableData.columns.join(', ')}) VALUES (${values.join(', ')});\n`;
    }
    sql += `\n`;
  }

  return sql;
}
